### PR TITLE
feature files, CukesRunner class, FailedTest runner class

### PR DESCRIPTION
**Pull request by elvirka7**
Added resources root folder, added features package and feature files for each user story

### CODE REVIEW

**Review by KseniiaKr — APPROVED** [review]
Guys, do you think it is more convenient to create 1 feature file per feature? For example 1 feature for Log in  with both positive and negative scenarios?

**Comment by elvirka7** [comment]
I think that’s how it’s gonna be in real life right? What does Asya want us
to do? So we are gonna have a few user stories in one feature  file? Like
US1 and US2 combined in one right?

**Comment by KseniiaKr** [comment]
Asked our PO. Will provide the update ASAP.

**Comment by KseniiaKr** [comment]
PO said one US=1 feature file.

**Pull request merged**
